-- ==============================================================================
-- SCHEMA SUPABASE: SuperEnalotto App
-- ==============================================================================

-- 1. UTENTI E ABBONAMENTI
-- ==============================================================================
CREATE TYPE subscription_tier_enum AS ENUM ('base', 'pro');

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    subscription_tier subscription_tier_enum DEFAULT 'base'::subscription_tier_enum,
    revenuecat_app_user_id TEXT, 
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Abilitiamo Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy: Ogni utente può leggere e aggiornare SOLO il proprio profilo
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- (Opzionale) Trigger per creare il profilo automaticamente alla registrazione
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. ARCHIVIO STORICO ESTRAZIONI
-- ==============================================================================
CREATE TABLE public.draws (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_date DATE NOT NULL UNIQUE,
    n1 SMALLINT NOT NULL,
    n2 SMALLINT NOT NULL,
    n3 SMALLINT NOT NULL,
    n4 SMALLINT NOT NULL,
    n5 SMALLINT NOT NULL,
    n6 SMALLINT NOT NULL,
    jolly SMALLINT,
    superstar SMALLINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indice sulla data per query temporali veloci
CREATE INDEX idx_draws_date ON public.draws(draw_date DESC);

-- RLS: Tutti possono leggere lo storico. 
-- L'inserimento verrà fatto con una Service Role Key.
ALTER TABLE public.draws ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access to draws" ON public.draws FOR SELECT USING (true);


-- 3. CACHE PREDITTIVA (ENSEMBLE ANALYTICS)
-- ==============================================================================
CREATE TABLE public.ensemble_predictions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    target_date DATE NOT NULL,
    model_version TEXT NOT NULL,
    suggested_sequence SMALLINT[] NOT NULL,
    confidence_score FLOAT4 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(target_date, model_version)
);

CREATE TABLE public.number_probabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_date DATE NOT NULL,
    probabilities JSONB NOT NULL,
    hot_numbers SMALLINT[] NOT NULL,
    cold_numbers SMALLINT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Solo gli utenti 'pro' possono leggere queste tabelle.
ALTER TABLE public.ensemble_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.number_probabilities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pro users can read predictions" 
ON public.ensemble_predictions 
FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND subscription_tier = 'pro'
    )
);

CREATE POLICY "Pro users can read probabilities" 
ON public.number_probabilities 
FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND subscription_tier = 'pro'
    )
);
